// Generated by Selenium IDE
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvFileSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.By;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class DateTest {
    private WebDriver driver;
    private ChromeOptions options;
    private Map<String, Object> vars;
    JavascriptExecutor js;


    @BeforeEach
    public void setUp() {
        options = new ChromeOptions().addArguments("--incognito");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }


    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @DisplayName("Expected")
    @ParameterizedTest()
    @CsvFileSource(resources = "dateTestExpected.csv")
    public void expectedCase(String printoutLink,String printoutCase, String start, String end, String url) throws InterruptedException {
        System.out.println(printoutLink + " " + printoutCase);
        driver.get(url);
        driver.manage().window().setSize(new Dimension(803, 816));
        Thread.sleep(5000);
        driver.findElement(By.xpath("//main[@id=\'site-content\']/div/div/div[3]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/button/div/div[2]")).click();
        Thread.sleep(1000);
        for (int i = 0; i < 9; i++){
            driver.findElement(By.id("checkIn-book_it")).sendKeys(Keys.BACK_SPACE);
            driver.findElement(By.id("checkIn-book_it")).sendKeys(Keys.DELETE);
        }

        Thread.sleep(1000);
        driver.findElement(By.id("checkIn-book_it")).sendKeys(start);
        Thread.sleep(1000);
        driver.findElement(By.id("checkOut-book_it")).click();
        Thread.sleep(1000);
        for (int i = 0; i < 9; i++){
            driver.findElement(By.id("checkOut-book_it")).sendKeys(Keys.BACK_SPACE);
            driver.findElement(By.id("checkOut-book_it")).sendKeys(Keys.DELETE);
        }
        Thread.sleep(1000);
        driver.findElement(By.id("checkOut-book_it")).sendKeys(end);
        Thread.sleep(1000);
        driver.findElement(By.id("checkOut-book_it")).sendKeys(Keys.ENTER);
        {
            WebElement element = driver.findElement(By.xpath("//main[@id=\'site-content\']/div/div/div[3]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/button/div/div[2]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }

        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
        //Check if Subtotal is displayed
        assertTrue(isElementPresent(driver, By.xpath("//main[@id=\'site-content\']/div/div/div[3]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div[3]/div/section/div[2]/div/span[2]/span/span")));
    }

    @DisplayName("unexpected")
    @ParameterizedTest
    @CsvFileSource(resources = "dateTestUnexpected.csv")
    public void unexpectedCase(String printoutLink,String printoutCase, String start, String end, String url) throws InterruptedException {
        System.out.println(printoutLink + " " + printoutCase);
        driver.get(url);
        driver.manage().window().setSize(new Dimension(803, 816));
        Thread.sleep(5000);
        driver.findElement(By.xpath("//main[@id=\'site-content\']/div/div/div[3]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/button/div/div[2]")).click();
        Thread.sleep(100);
        for (int i = 0; i < 9; i++){
            driver.findElement(By.id("checkIn-book_it")).sendKeys(Keys.BACK_SPACE);
            driver.findElement(By.id("checkIn-book_it")).sendKeys(Keys.DELETE);
        }

        Thread.sleep(100);
        driver.findElement(By.id("checkIn-book_it")).sendKeys(start);
        Thread.sleep(100);
        driver.findElement(By.id("checkOut-book_it")).click();
        if (isElementPresent(driver,By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[1]/div[1]/div[2]/div"))
            || driver.findElement(By.id("checkOut-book_it")).getText().isEmpty()){
            assertTrue(true);
            return;
        }

        Thread.sleep(100);
        for (int i = 0; i < 9; i++){
            driver.findElement(By.id("checkOut-book_it")).sendKeys(Keys.BACK_SPACE);
            driver.findElement(By.id("checkOut-book_it")).sendKeys(Keys.DELETE);
        }
        Thread.sleep(100);
        driver.findElement(By.id("checkOut-book_it")).sendKeys(end);
        Thread.sleep(100);
        driver.findElement(By.id("checkOut-book_it")).sendKeys(Keys.ENTER);


        System.out.println(driver.findElement(By.id("checkOut-book_it")).getText());
        //Check if checkout date is not accepted by the frontend
        assertTrue(isElementPresent(driver,By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[1]/div[1]/div[2]/div")));

        //click out of calendar
        driver.findElement(By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[1]/div/div[1]/div/div/div/section/div[1]")).click();


        js.executeScript("window.scrollTo(0,644)");
        assertThrows(org.openqa.selenium.NoSuchElementException.class, () -> {
            driver.findElement(By.cssSelector(".\\_18x3iiu > div")).click();
        });



        //Check if Subtotal is not displayed
        assertFalse(isElementPresent(driver, By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div[3]")));
    }


    public static boolean isElementPresent(WebDriver driver, By by) {
        try {
            WebElement element = driver.findElement(by);
            return element.isDisplayed();
        } catch (org.openqa.selenium.NoSuchElementException e) {
            return false;
        }
    }
}