// Generated by Selenium IDE
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.By;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class DateTest {
    private WebDriver driver;
    private ChromeOptions options;
    private Map<String, Object> vars;
    JavascriptExecutor js;


    @BeforeEach
    public void setUp() {
        options = new ChromeOptions().addArguments("--incognito");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }


    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @DisplayName("Accepted")
    @Test
    public void acceptedCase() {
        driver.get("https://www.airbnb.com/rooms/33677783?adults=1&category_tag=Tag%3A8678&children=0&enable_m3_private_room=true&infants=0&pets=0&photo_id=1640221161&search_mode=flex_destinations_search&check_in=2024-06-11&check_out=2024-06-16&source_impression_id=p3_1716217522_PGaN8IJ8vQTHwXGY&previous_page_section_name=1000&federated_search_id=b3108ee2-4faf-4f73-b2e2-906c11e28f7b");
        driver.manage().window().setSize(new Dimension(800, 816));
        js.executeScript("window.scrollTo(0,0.800000011920929)");
        js.executeScript("window.scrollTo(0,172.8000030517578)");

        //Wait for page to load
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.findElement(By.xpath("/html/body/div[9]/div/div/section/div/div/div[2]/div/div[1]")).click();
        driver.findElement(By.cssSelector(".\\_19y8o0j > .\\_tekaj0")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".\\_1ie8utng .l1ovpqvx"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }


        //Enter Checkin Date
        WebElement dateFieldCheckIn = driver.findElement(By.id("checkIn-book_it"));
        dateFieldCheckIn.clear();
        dateFieldCheckIn.sendKeys("\b\b\b\b\b\b\b\b\b\b\b\b");
        dateFieldCheckIn.sendKeys("6/13/2024");
        driver.findElement(By.cssSelector(".\\_1ie8utng")).click();
        driver.findElement(By.id("checkOut-book_it")).click();
        driver.findElement(By.id("checkOut-book_it")).click();

        //Enter Checkout Date
        WebElement dateFieldCheckOut = driver.findElement(By.id("checkOut-book_it"));
        dateFieldCheckOut.clear();
        dateFieldCheckOut.sendKeys("\b\b\b\b\b\b\b\b\b\b\b\b");
        dateFieldCheckOut.sendKeys("6/17/2024");
        driver.findElement(By.id("checkOut-book_it")).sendKeys(Keys.ENTER);

        //Check if checkout date is accepted by frontend
        assertFalse(isElementPresent(driver,By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[1]/div[1]/div[2]/div")));

        //Click out of calendar
        js.executeScript("window.scrollTo(0,644)");
        driver.findElement(By.cssSelector(".\\_18x3iiu > div")).click();

        //Check if Subtotal is displayed
        assertTrue(isElementPresent(driver, By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div[3]")));
    }

    @DisplayName("unexpected")
    @Test
    public void unexpectedCase() {
        driver.get("https://www.airbnb.com/rooms/33677783?adults=1&category_tag=Tag%3A8678&children=0&enable_m3_private_room=true&infants=0&pets=0&photo_id=1640221161&search_mode=flex_destinations_search&check_in=2024-06-11&check_out=2024-06-16&source_impression_id=p3_1716217522_PGaN8IJ8vQTHwXGY&previous_page_section_name=1000&federated_search_id=b3108ee2-4faf-4f73-b2e2-906c11e28f7b");
        driver.manage().window().setSize(new Dimension(800, 816));
        js.executeScript("window.scrollTo(0,0.800000011920929)");
        js.executeScript("window.scrollTo(0,172.8000030517578)");

        //Wait for page to load
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.findElement(By.xpath("/html/body/div[9]/div/div/section/div/div/div[2]/div/div[1]")).click();
        driver.findElement(By.cssSelector(".\\_19y8o0j > .\\_tekaj0")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".\\_1ie8utng .l1ovpqvx"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }


        //Enter Checkin Date
        WebElement dateFieldCheckIn = driver.findElement(By.id("checkIn-book_it"));
        dateFieldCheckIn.clear();
        dateFieldCheckIn.sendKeys("\b\b\b\b\b\b\b\b\b\b\b\b");
        dateFieldCheckIn.sendKeys("6/13/2024");
        driver.findElement(By.cssSelector(".\\_1ie8utng")).click();
        driver.findElement(By.id("checkOut-book_it")).click();
        driver.findElement(By.id("checkOut-book_it")).click();

        //Enter Checkout Date
        WebElement dateFieldCheckOut = driver.findElement(By.id("checkOut-book_it"));
        dateFieldCheckOut.clear();
        dateFieldCheckOut.sendKeys("\b\b\b\b\b\b\b\b\b\b\b\b");
        dateFieldCheckOut.sendKeys("6/12/2024");
        driver.findElement(By.id("checkOut-book_it")).sendKeys(Keys.ENTER);

        //Check if checkout date is not accepted by the frontend
        assertTrue(isElementPresent(driver,By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[1]/div[1]/div[2]/div")));

        //click out of calendar
        driver.findElement(By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[1]/div/div[1]/div/div/div/section/div[1]")).click();


        js.executeScript("window.scrollTo(0,644)");
        assertThrows(org.openqa.selenium.NoSuchElementException.class, () -> {
            driver.findElement(By.cssSelector(".\\_18x3iiu > div")).click();
        });



        //Check if Subtotal is not displayed
        assertFalse(isElementPresent(driver, By.xpath("/html/body/div[5]/div/div/div[1]/div/div[2]/div/div/div/div[1]/main/div/div[1]/div[3]/div/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div[3]")));
    }


    public static boolean isElementPresent(WebDriver driver, By by) {
        try {
            WebElement element = driver.findElement(by);
            return element.isDisplayed();
        } catch (org.openqa.selenium.NoSuchElementException e) {
            return false;
        }
    }
}